include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - annotate_overrides
    - hash_and_equals
    - prefer_is_not_empty
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements